import {
  Phone, MessageSquare, Mail, Clock, Contact, Settings,
  Calculator, CalendarDays, StickyNote, Aperture,
  Cloud, Croissant, Atom, Bug, Cat, Moon, Radar, Rocket,
  Flame, Carrot, Music, Footprints, Grid3x3, Tv, Egg, Leaf,
  Mountain, Zap, Megaphone, TreePine, Cherry, Drum, Gamepad2,
  Dumbbell, Pizza, Anchor, Feather, Ghost, Anvil, Binoculars,
  Flower2, Key, Camera, Wallet, Dices, Heart,
  Navigation, PenTool, ShieldCheck, Landmark, Gem, Telescope, Type, Coins,
  Sun, Bird, Globe, Star, Binary, Clapperboard,
} from "lucide-react";

export const coreApps = [
  { id: "phone", label: "Phone", Icon: Phone, bg: "#34C759" },
  { id: "messages", label: "Messages", Icon: MessageSquare, bg: "#34C759" },
  { id: "email", label: "Mail", Icon: Mail, bg: "#0A84FF" },
  { id: "clock", label: "Clock", Icon: Clock, bg: "#FF9F0A" },
  { id: "contacts", label: "Contacts", Icon: Contact, bg: "#5A5D6B" },
  { id: "settings", label: "Settings", Icon: Settings, bg: "#636366" },
  { id: "calculator", label: "Calculator", Icon: Calculator, bg: "#1C1C1E" },
  { id: "calendar", label: "Calendar", Icon: CalendarDays, bg: "#FF3B30" },
  { id: "notes", label: "Notes", Icon: StickyNote, bg: "#FFC800", tile: { type: "gloss", fg: "#7A5900" } },
  { id: "camera", label: "Camera", Icon: Aperture, bg: "#2C2C2E" },
];

// mock ("downloaded") apps — each with its own tile style
export const mockApps = [
  { id: "nimbus", label: "Nimbus", Icon: Cloud, bg: "#5E5CE6", tile: { type: "duo", bg2: "#A78BFA" } },
  { id: "snacc", label: "Snacc", Icon: Croissant, bg: "#FF9F0A", tile: { type: "flat" } },
  { id: "quantum", label: "Quantum", Icon: Atom, bg: "#22D3EE", tile: { type: "outline" } },
  { id: "womp", label: "Wompwomp", Icon: Bug, bg: "#FF453A", tile: { type: "dark" } },
  { id: "chonk", label: "Chonk", Icon: Cat, bg: "#FFB340", tile: { type: "gloss" } },
  { id: "dozer", label: "Dozer", Icon: Moon, bg: "#7C3AED", tile: { type: "mono" } },
  { id: "blip", label: "Blip", Icon: Radar, bg: "#16A34A", tile: { type: "stripes", bg2: "#166534" } },
  { id: "skrrt", label: "Skrrt", Icon: Rocket, bg: "#FF375F", tile: { type: "gloss" } },
  { id: "glowstick", label: "Glowstick", Icon: Flame, bg: "#FF6B00", tile: { type: "dark" } },
  { id: "turnip", label: "Turnip", Icon: Carrot, bg: "#FF6B35", tile: { type: "flat" } },
  { id: "kazoo", label: "Kazoo", Icon: Music, bg: "#8B5CF6", tile: { type: "duo", bg2: "#D946EF" } },
  { id: "puddles", label: "Puddles", Icon: Footprints, bg: "#60A5FA", tile: { type: "outline" } },
  { id: "waffle", label: "Waffle", Icon: Grid3x3, bg: "#F97316", tile: { type: "mono" } },
  { id: "static", label: "Static", Icon: Tv, bg: "#4ADE80", tile: { type: "dark" } },
  { id: "cluck", label: "Cluck", Icon: Egg, bg: "#FDE68A", tile: { type: "gloss", fg: "#92400E" } },
  { id: "mossy", label: "Mossy", Icon: Leaf, bg: "#30D158", tile: { type: "flat" } },
  { id: "rubble", label: "Rubble", Icon: Mountain, bg: "#78716C", tile: { type: "duo", bg2: "#A8A29E" } },
  { id: "zaplet", label: "Zaplet", Icon: Zap, bg: "#FFD60A", tile: { type: "ring", bg2: "#FF9F0A", fg: "#783509" } },
  { id: "honk", label: "Honk", Icon: Megaphone, bg: "#FF375F", tile: { type: "flat" } },
  { id: "lumber", label: "Lumber", Icon: TreePine, bg: "#166534", tile: { type: "duo", bg2: "#22C55E" } },
  { id: "squish", label: "Squish", Icon: Cherry, bg: "#FF6482", tile: { type: "gloss" } },
  { id: "rumble", label: "Rumble", Icon: Drum, bg: "#B45309", tile: { type: "stripes", bg2: "#FCD34D", fg: "#451A03" } },
  { id: "pixel", label: "Pixel", Icon: Gamepad2, bg: "#A78BFA", tile: { type: "dark" } },
  { id: "swole", label: "Swole", Icon: Dumbbell, bg: "#FF9F0A", tile: { type: "gloss" } },
  { id: "slice", label: "Slice", Icon: Pizza, bg: "#FF453A", tile: { type: "flat" } },
  { id: "moor", label: "Moor", Icon: Anchor, bg: "#64748B", tile: { type: "dark" } },
  { id: "plume", label: "Plume", Icon: Feather, bg: "#F472B6", tile: { type: "outline" } },
  { id: "spooky", label: "Spooky", Icon: Ghost, bg: "#8B5CF6", tile: { type: "dark" } },
  { id: "clank", label: "Clank", Icon: Anvil, bg: "#57534E", tile: { type: "duo", bg2: "#A8A29E" } },
  { id: "peeper", label: "Peeper", Icon: Binoculars, bg: "#16A34A", tile: { type: "mono" } },
  { id: "petal", label: "Petal", Icon: Flower2, bg: "#FFD60A", tile: { type: "gloss", fg: "#783509" } },
  { id: "keyring", label: "Keyring", Icon: Key, bg: "#FBBF24", tile: { type: "flat" } },
  { id: "paparazzi", label: "Paparazzi", Icon: Camera, bg: "#374151", tile: { type: "dark" } },
  { id: "banky", label: "Banky", Icon: Wallet, bg: "#166534", tile: { type: "duo", bg2: "#22C55E" } },
  { id: "roll", label: "Roll", Icon: Dices, bg: "#F8FAFC", tile: { type: "gloss", fg: "#1E293B" } },
  { id: "heartthrob", label: "Heartthrob", Icon: Heart, bg: "#FF2D55", tile: { type: "gloss" } },
  { id: "meridian", label: "Meridian", Icon: Navigation, bg: "#0E7490", tile: { type: "flat" } },
  { id: "quill", label: "Quill", Icon: PenTool, bg: "#0F172A", tile: { type: "mono" } },
  { id: "vault", label: "Vault", Icon: ShieldCheck, bg: "#312E81", tile: { type: "dark" } },
  { id: "ledger", label: "Ledger", Icon: Landmark, bg: "#0F766E", tile: { type: "flat" } },
  { id: "obsidian", label: "Obsidian", Icon: Gem, bg: "#111827", tile: { type: "gloss" } },
  { id: "astra", label: "Astra", Icon: Telescope, bg: "#1E1B4B", tile: { type: "dark" } },
  { id: "monogram", label: "Monogram", Icon: Type, bg: "#1C1917", tile: { type: "mono" } },
  { id: "argent", label: "Argent", Icon: Coins, bg: "#475569", tile: { type: "duo", bg2: "#94A3B8" } },
  { id: "solstice", label: "Solstice", Icon: Sun, bg: "#F59E0B", tile: { type: "mono" } },
  { id: "cardinal", label: "Cardinal", Icon: Bird, bg: "#7F1D1D", tile: { type: "flat" } },
  { id: "terra", label: "Terra", Icon: Globe, bg: "#166534", tile: { type: "duo", bg2: "#22C55E" } },
  { id: "nova", label: "Nova", Icon: Star, bg: "#312E81", tile: { type: "gloss" } },
  { id: "premiere", label: "Premiere", Icon: Clapperboard, bg: "#FF375F", tile: { type: "dark" } },
  { id: "cipher", label: "Cipher", Icon: Binary, bg: "#1E1B4B", tile: { type: "outline" } },
];

export const allApps = [...coreApps, ...mockApps];

export const allAppsById = Object.fromEntries(allApps.map((a) => [a.id, a]));