import 'package:flutter/material.dart';

import '../models.dart';

/// Five ATM skins. An empty shell is Night.
class AtmSkin {
  const AtmSkin({
    required this.id,
    required this.name,
    required this.light,
    required this.washA,
    required this.washB,
    required this.washC,
    required this.major,
    required this.majorInk,
    required this.minor,
    required this.minorInk,
    required this.title,
    required this.muted,
    required this.keyFill,
    required this.keyInk,
    required this.primary,
    required this.primaryInk,
    required this.rule,
  });

  final String id;
  final String name;
  final bool light;
  final Color washA;
  final Color washB;
  final Color washC;
  final Color major;
  final Color majorInk;
  final Color minor;
  final Color minorInk;
  final Color title;
  final Color muted;
  final Color keyFill;
  final Color keyInk;
  final Color primary;
  final Color primaryInk;
  final Color rule;
}

const kAtmSkins = <AtmSkin>[
  AtmSkin(
    id: 'night',
    name: 'Night',
    light: false,
    washA: Color(0xFF221C38),
    washB: Color(0xFF14121C),
    washC: Color(0xFF10141E),
    major: Color(0xFFF4F1EA),
    majorInk: Color(0xFF16141C),
    minor: Color(0xFF221F2C),
    minorInk: Colors.white,
    title: Colors.white,
    muted: Color(0xFFB7B3C7),
    keyFill: Color(0xFF2A2638),
    keyInk: Colors.white,
    primary: Color(0xFFF4F1EA),
    primaryInk: Color(0xFF16141C),
    rule: Color(0x22FFFFFF),
  ),
  AtmSkin(
    id: 'daylight',
    name: 'Daylight',
    light: true,
    washA: Color(0xFFD7E6F5),
    washB: Color(0xFFF4F8FC),
    washC: Color(0xFFE4EEF8),
    major: Color(0xFF1D6FEA),
    majorInk: Colors.white,
    minor: Colors.white,
    minorInk: Color(0xFF16324F),
    title: Color(0xFF102033),
    muted: Color(0xFF4C6278),
    keyFill: Colors.white,
    keyInk: Color(0xFF102033),
    primary: Color(0xFF1D6FEA),
    primaryInk: Colors.white,
    rule: Color(0x2216324F),
  ),
  AtmSkin(
    id: 'gold',
    name: 'Gold',
    light: false,
    washA: Color(0xFF1A1A1A),
    washB: Color(0xFF121212),
    washC: Color(0xFF0C0C0C),
    major: Color(0xFFF5C400),
    majorInk: Color(0xFF1A1400),
    minor: Color(0xFF2A2A2A),
    minorInk: Color(0xFFF5C400),
    title: Colors.white,
    muted: Color(0xFFD0D0D0),
    keyFill: Color(0xFF2A2A2A),
    keyInk: Colors.white,
    primary: Color(0xFFF5C400),
    primaryInk: Color(0xFF1A1400),
    rule: Color(0x33F5C400),
  ),
  AtmSkin(
    id: 'harbor',
    name: 'Harbor',
    light: false,
    washA: Color(0xFF0C2420),
    washB: Color(0xFF102C28),
    washC: Color(0xFF081816),
    major: Color(0xFFE7F4EC),
    majorInk: Color(0xFF10241C),
    minor: Color(0xFF1A3330),
    minorInk: Colors.white,
    title: Colors.white,
    muted: Color(0xFFB7C9C2),
    keyFill: Color(0xFF1A3330),
    keyInk: Colors.white,
    primary: Color(0xFFE7F4EC),
    primaryInk: Color(0xFF10241C),
    rule: Color(0x33FFFFFF),
  ),
  AtmSkin(
    id: 'paper',
    name: 'Paper',
    light: true,
    washA: Color(0xFFF4EFE6),
    washB: Color(0xFFE7E0D4),
    washC: Color(0xFFFBF7F1),
    major: Color(0xFF2A2622),
    majorInk: Color(0xFFF4EFE6),
    minor: Color(0xFFFFFCF7),
    minorInk: Color(0xFF2A2622),
    title: Color(0xFF2A2622),
    muted: Color(0xFF6E675E),
    keyFill: Color(0xFFFFFCF7),
    keyInk: Color(0xFF2A2622),
    primary: Color(0xFF2A2622),
    primaryInk: Color(0xFFF4EFE6),
    rule: Color(0x332A2622),
  ),
];

const kAtmCurrencies = ['USD', 'EUR', 'GBP', 'JPY', 'CAD'];

const kAtmPanelIds = [
  'withdraw',
  'deposit',
  'balance',
  'bills',
  'statement',
  'transfer',
  'settings',
  'take',
];

AtmSkin atmSkinFor(String id) {
  for (final skin in kAtmSkins) {
    if (skin.id == id) return skin;
  }
  return kAtmSkins.first;
}

List<String> atmPanels(OsSettings os) {
  final saved = [
    for (final id in os.homeOrder)
      if (kAtmPanelIds.contains(id)) id,
  ];
  if (saved.length != kAtmPanelIds.length ||
      saved.toSet().length != kAtmPanelIds.length) {
    return kAtmPanelIds;
  }
  return saved;
}

String atmLine(String language, String key) {
  final pack = _packs[language];
  return pack?[key] ?? _en[key] ?? key;
}

String atmFill(String language, String key, Map<String, String> values) {
  var line = atmLine(language, key);
  for (final entry in values.entries) {
    line = line.replaceAll('{${entry.key}}', entry.value);
  }
  return line;
}

String atmGreeting(String language, int hour, String name) {
  final key = hour < 12
      ? 'morning'
      : hour < 17
      ? 'afternoon'
      : 'evening';
  return atmFill(language, key, {'name': name});
}

const _en = <String, String>{
  'enterPin': 'Enter PIN',
  'pinHint': 'Any 5 digits unlock this machine.',
  'morning': 'Good Morning, {name}',
  'afternoon': 'Good Afternoon, {name}',
  'evening': 'Good Evening, {name}',
  'select': 'Please select your transaction',
  'withdraw': 'Money\nWithdrawal',
  'deposit': 'Money\nDeposit',
  'balance': 'Balance Inquiry',
  'bills': 'Bill Payment',
  'statement': 'Mini Statement',
  'transfer': 'Internal Transfer',
  'settings': 'Settings',
  'take': 'Take card',
  'whichAccount': 'Which account?',
  'checking': 'Checking',
  'savings': 'Savings',
  'cancel': 'Cancel',
  'chooseAmount': 'Choose an amount',
  'available': '{account} · {currency} {balance} available',
  'confirmWithdrawal': 'Confirm withdrawal',
  'fromAccount': '{currency} {amount} from {account}',
  'takeCash': 'Please take your cash',
  'cashTaken': 'Cash taken',
  'receiptAsk': 'Would you like a receipt?',
  'printReceipt': 'Print receipt',
  'noReceipt': 'No receipt',
  'receipt': 'Receipt',
  'finish': 'Finish',
  'another': 'Another transaction?',
  'yes': 'Yes',
  'no': 'No',
  'takeCard': 'Please take your card',
  'sessionDone': 'This session is finished.',
  'done': 'Done',
  'depositTitle': 'Deposit',
  'depositHint': 'Choose an amount to add.',
  'confirmDeposit': 'Confirm deposit',
  'intoChecking': '{currency} {amount} into Checking',
  'accepted': '{action} accepted',
  'balanceTitle': 'Balance Inquiry',
  'anotherTx': 'Another transaction',
  'transferTitle': 'Internal transfer',
  'transferBody': 'Move {currency} 50 from Checking to Savings.',
  'confirmTransfer': 'Confirm transfer',
  'billTitle': 'Bill payment',
  'billBody': 'Power · {currency} 40',
  'pay': 'Pay',
  'statementTitle': 'Mini statement',
  'statementBody':
      'Market · {currency} 18\nTransit · {currency} 12\nPower · {currency} 40',
  'out': 'Out of service',
  'closed': 'This machine is closed.',
  'restore': 'Restore',
  'service': 'Service',
  'unable': 'Unable to continue',
  'unavailable': 'That amount is not available.',
  'back': 'Back',
  'settingsTitle': 'Settings',
  'theme': 'Theme',
  'currency': 'Currency',
  'language': 'Language',
  'background': 'Background',
  'upload': 'Upload background',
  'removeBg': 'Remove background',
  'panels': 'Panels',
  'editLayout': 'Edit layout',
  'layoutHint': 'Tap two panels to swap them.',
  'actWithdraw': 'Withdrawal',
  'actDeposit': 'Deposit',
  'actBalance': 'Balance',
  'actTransfer': 'Transfer',
  'actBill': 'Bill payment',
};

const _packs = <String, Map<String, String>>{
  'en': _en,
  'es': {
    'enterPin': 'Introduzca el PIN',
    'pinHint': 'Cualquier número de 5 dígitos abre esta máquina.',
    'morning': 'Buenos días, {name}',
    'afternoon': 'Buenas tardes, {name}',
    'evening': 'Buenas noches, {name}',
    'select': 'Seleccione su transacción',
    'withdraw': 'Retiro\nde dinero',
    'deposit': 'Depósito\nde dinero',
    'balance': 'Consulta de saldo',
    'bills': 'Pago de facturas',
    'statement': 'Mini extracto',
    'transfer': 'Transferencia interna',
    'settings': 'Ajustes',
    'take': 'Retirar tarjeta',
    'whichAccount': '¿Qué cuenta?',
    'checking': 'Cuenta corriente',
    'savings': 'Ahorros',
    'cancel': 'Cancelar',
    'chooseAmount': 'Elija un importe',
    'available': '{account} · {currency} {balance} disponible',
    'confirmWithdrawal': 'Confirmar retiro',
    'fromAccount': '{currency} {amount} de {account}',
    'takeCash': 'Retire su efectivo',
    'cashTaken': 'Efectivo retirado',
    'receiptAsk': '¿Desea un recibo?',
    'printReceipt': 'Imprimir recibo',
    'noReceipt': 'Sin recibo',
    'receipt': 'Recibo',
    'finish': 'Terminar',
    'another': '¿Otra transacción?',
    'yes': 'Sí',
    'no': 'No',
    'takeCard': 'Retire su tarjeta',
    'sessionDone': 'La sesión ha terminado.',
    'done': 'Listo',
    'depositTitle': 'Depósito',
    'depositHint': 'Elija un importe.',
    'confirmDeposit': 'Confirmar depósito',
    'intoChecking': '{currency} {amount} en Cuenta corriente',
    'accepted': '{action} aceptado',
    'balanceTitle': 'Consulta de saldo',
    'anotherTx': 'Otra transacción',
    'transferTitle': 'Transferencia interna',
    'transferBody': 'Mover {currency} 50 de Cuenta corriente a Ahorros.',
    'confirmTransfer': 'Confirmar transferencia',
    'billTitle': 'Pago de facturas',
    'pay': 'Pagar',
    'statementTitle': 'Mini extracto',
    'out': 'Fuera de servicio',
    'closed': 'Esta máquina está cerrada.',
    'restore': 'Restablecer',
    'service': 'Servicio',
    'unable': 'No se puede continuar',
    'unavailable': 'Ese importe no está disponible.',
    'back': 'Volver',
    'settingsTitle': 'Ajustes',
    'theme': 'Tema',
    'currency': 'Moneda',
    'language': 'Idioma',
    'background': 'Fondo',
    'upload': 'Subir fondo',
    'removeBg': 'Quitar fondo',
    'panels': 'Paneles',
    'editLayout': 'Editar paneles',
    'layoutHint': 'Toque dos paneles para intercambiarlos.',
    'actWithdraw': 'Retiro',
    'actDeposit': 'Depósito',
    'actBalance': 'Saldo',
    'actTransfer': 'Transferencia',
    'actBill': 'Pago',
  },
  'fr': {
    'enterPin': 'Saisissez le PIN',
    'pinHint': "N'importe quel code à 5 chiffres ouvre cette machine.",
    'morning': 'Bonjour, {name}',
    'afternoon': 'Bon après-midi, {name}',
    'evening': 'Bonsoir, {name}',
    'select': 'Choisissez votre opération',
    'withdraw': 'Retrait\nd’argent',
    'deposit': 'Dépôt\nd’argent',
    'balance': 'Consultation du solde',
    'bills': 'Paiement de facture',
    'statement': 'Mini relevé',
    'transfer': 'Virement interne',
    'settings': 'Réglages',
    'take': 'Retirer la carte',
    'settingsTitle': 'Réglages',
    'theme': 'Thème',
    'currency': 'Devise',
    'language': 'Langue',
    'background': 'Fond',
    'upload': 'Importer un fond',
    'removeBg': 'Retirer le fond',
    'panels': 'Panneaux',
    'editLayout': 'Modifier la disposition',
    'layoutHint': 'Touchez deux panneaux pour les échanger.',
    'whichAccount': 'Quel compte ?',
    'checking': 'Compte courant',
    'savings': 'Épargne',
    'cancel': 'Annuler',
    'chooseAmount': 'Choisissez un montant',
    'confirmWithdrawal': 'Confirmer le retrait',
    'takeCash': 'Veuillez prendre vos billets',
    'cashTaken': 'Billets pris',
    'receiptAsk': 'Souhaitez-vous un reçu ?',
    'done': 'Terminé',
    'back': 'Retour',
  },
  'de': {
    'enterPin': 'PIN eingeben',
    'pinHint': 'Jede 5-stellige Zahl öffnet diesen Automaten.',
    'morning': 'Guten Morgen, {name}',
    'afternoon': 'Guten Tag, {name}',
    'evening': 'Guten Abend, {name}',
    'select': 'Bitte Vorgang wählen',
    'withdraw': 'Geld\nabheben',
    'deposit': 'Geld\neinzahlen',
    'balance': 'Kontostand',
    'bills': 'Rechnung zahlen',
    'statement': 'Kontoauszug',
    'transfer': 'Interne Überweisung',
    'settings': 'Einstellungen',
    'take': 'Karte entnehmen',
    'settingsTitle': 'Einstellungen',
    'theme': 'Thema',
    'currency': 'Währung',
    'language': 'Sprache',
    'background': 'Hintergrund',
    'upload': 'Hintergrund hochladen',
    'removeBg': 'Hintergrund entfernen',
    'panels': 'Felder',
    'editLayout': 'Anordnung ändern',
    'layoutHint': 'Zwei Felder antippen, um sie zu tauschen.',
    'whichAccount': 'Welches Konto?',
    'checking': 'Girokonto',
    'savings': 'Sparen',
    'cancel': 'Abbrechen',
    'chooseAmount': 'Betrag wählen',
    'confirmWithdrawal': 'Abhebung bestätigen',
    'takeCash': 'Bitte Geld entnehmen',
    'cashTaken': 'Geld entnommen',
    'done': 'Fertig',
    'back': 'Zurück',
  },
  'ja': {
    'enterPin': '暗証番号を入力',
    'pinHint': '5桁の数字で開きます。',
    'morning': 'おはようございます、{name}',
    'afternoon': 'こんにちは、{name}',
    'evening': 'こんばんは、{name}',
    'select': 'お取引を選択してください',
    'withdraw': 'お引き出し',
    'deposit': 'ご入金',
    'balance': '残高照会',
    'bills': 'お支払い',
    'statement': 'ご利用明細',
    'transfer': '振込',
    'settings': '設定',
    'take': 'カードをお取りください',
    'settingsTitle': '設定',
    'theme': 'テーマ',
    'currency': '通貨',
    'language': '言語',
    'background': '背景',
    'upload': '背景をアップロード',
    'removeBg': '背景を消す',
    'panels': 'パネル',
    'editLayout': '配置を編集',
    'layoutHint': '2つのパネルをタップして入れ替えます。',
    'whichAccount': '口座を選択',
    'checking': '普通預金',
    'savings': '貯蓄',
    'cancel': '取消',
    'chooseAmount': '金額を選択',
    'confirmWithdrawal': '出金を確認',
    'takeCash': '現金をお取りください',
    'cashTaken': '受け取りました',
    'done': '完了',
    'back': '戻る',
  },
  'zh': {
    'enterPin': '请输入密码',
    'pinHint': '任意 5 位数字即可解锁。',
    'morning': '早上好，{name}',
    'afternoon': '下午好，{name}',
    'evening': '晚上好，{name}',
    'select': '请选择交易',
    'withdraw': '取款',
    'deposit': '存款',
    'balance': '余额查询',
    'bills': '缴费',
    'statement': '迷你对账单',
    'transfer': '行内转账',
    'settings': '设置',
    'take': '取回卡片',
    'settingsTitle': '设置',
    'theme': '主题',
    'currency': '货币',
    'language': '语言',
    'background': '背景',
    'upload': '上传背景',
    'removeBg': '移除背景',
    'panels': '面板',
    'editLayout': '编辑布局',
    'layoutHint': '点按两个面板即可对调。',
  },
  'pt': {
    'select': 'Selecione a transação',
    'withdraw': 'Levantamento',
    'deposit': 'Depósito',
    'balance': 'Consulta de saldo',
    'bills': 'Pagamento',
    'statement': 'Extrato',
    'transfer': 'Transferência',
    'settings': 'Definições',
    'take': 'Retirar cartão',
    'settingsTitle': 'Definições',
    'theme': 'Tema',
    'currency': 'Moeda',
    'language': 'Idioma',
    'background': 'Fundo',
    'upload': 'Carregar fundo',
    'removeBg': 'Remover fundo',
    'panels': 'Painéis',
    'editLayout': 'Editar disposição',
    'layoutHint': 'Toque em dois painéis para os trocar.',
  },
  'it': {
    'select': 'Seleziona l’operazione',
    'withdraw': 'Prelievo',
    'deposit': 'Versamento',
    'balance': 'Saldo',
    'bills': 'Pagamento',
    'statement': 'Estratto',
    'transfer': 'Bonifico interno',
    'settings': 'Impostazioni',
    'take': 'Ritira la carta',
    'settingsTitle': 'Impostazioni',
    'theme': 'Tema',
    'currency': 'Valuta',
    'language': 'Lingua',
    'background': 'Sfondo',
    'upload': 'Carica sfondo',
    'removeBg': 'Rimuovi sfondo',
    'panels': 'Pannelli',
    'editLayout': 'Modifica layout',
    'layoutHint': 'Tocca due pannelli per scambiarli.',
  },
  'nl': {
    'select': 'Kies uw transactie',
    'settings': 'Instellingen',
    'settingsTitle': 'Instellingen',
    'theme': 'Thema',
    'currency': 'Valuta',
    'language': 'Taal',
    'background': 'Achtergrond',
    'upload': 'Achtergrond uploaden',
    'removeBg': 'Achtergrond verwijderen',
    'panels': 'Panelen',
    'editLayout': 'Indeling wijzigen',
    'layoutHint': 'Tik twee panelen om ze te wisselen.',
  },
};
